# SMS DATA

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("sms.tsv",sep="\t",names=["label","SMS"])

In [3]:
df.head()

  label                                                SMS
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.shape

(5572, 2)

In [5]:
df.size

11144

In [6]:
df["label"].value_counts()

ham     4825
spam     747
Name: label, dtype: int64

In [7]:
df.replace({"ham":0,"spam":1},inplace=True)
df.head()

   label                                                SMS
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [8]:
#import and instantiate CountVectorizer(with default parameters)
from sklearn.feature_extraction.text import CountVectorizer
vect=CountVectorizer()

In [9]:
#learn the "vocabulary" of training data
vect.fit(df.SMS)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [10]:
#examine the fitted vocabulary
vect.get_feature_names()

['00',
 '000',
 '000pes',
 '008704050406',
 '0089',
 '0121',
 '01223585236',
 '01223585334',
 '0125698789',
 '02',
 '0207',
 '02072069400',
 '02073162414',
 '02085076972',
 '021',
 '03',
 '04',
 '0430',
 '05',
 '050703',
 '0578',
 '06',
 '07',
 '07008009200',
 '07046744435',
 '07090201529',
 '07090298926',
 '07099833605',
 '07123456789',
 '0721072',
 '07732584351',
 '07734396839',
 '07742676969',
 '07753741225',
 '0776xxxxxxx',
 '07781482378',
 '07786200117',
 '077xxx',
 '078',
 '07801543489',
 '07808',
 '07808247860',
 '07808726822',
 '07815296484',
 '07821230901',
 '078498',
 '07880867867',
 '0789xxxxxxx',
 '07946746291',
 '0796xxxxxx',
 '07973788240',
 '07xxxxxxxxx',
 '08',
 '0800',
 '08000407165',
 '08000776320',
 '08000839402',
 '08000930705',
 '08000938767',
 '08001950382',
 '08002888812',
 '08002986030',
 '08002986906',
 '08002988890',
 '08006344447',
 '0808',
 '08081263000',
 '08081560665',
 '0825',
 '083',
 '0844',
 '08448350055',
 '08448714184',
 '0845',
 '08450542832',
 '08452810071',
 '08452810073',
 '08452810075over18',
 '0870',
 '08700435505150p',
 '08700469649',
 '08700621170150p',
 '08701213186',
 '08701237397',
 '08701417012',
 '08701417012150p',
 '0870141701216',
 '087016248',
 '08701752560',
 '087018728737',
 '0870241182716',
 '08702490080',
 '08702840625',
 '08704050406',
 '08704439680',
 '08704439680ts',
 '08706091795',
 '0870737910216yrs',
 '08707500020',
 '08707509020',
 '0870753331018',
 '08707808226',
 '08708034412',
 '08708800282',
 '08709222922',
 '08709501522',
 '0871',
 '087104711148',
 '08712101358',
 '08712103738',
 '0871212025016',
 '08712300220',
 '087123002209am',
 '08712317606',
 '08712400200',
 '08712400602450p',
 '08712400603',
 '08712402050',
 '08712402578',
 '08712402779',
 '08712402902',
 '08712402972',
 '08712404000',
 '08712405020',
 '08712405022',
 '08712460324',
 '08712466669',
 '0871277810710p',
 '0871277810810',
 '0871277810910p',
 '08714342399',
 '087147123779am',
 '08714712379',
 '08714712388',
 '08714712394',
 '08714712412',
 '08714714011',
 '08715203028',
 '08715203649',
 '08715203652',
 '08715203656',
 '08715203677',
 '08715203685',
 '08715203694',
 '08715205273',
 '08715500022',
 '08715705022',
 '08717111821',
 '08717168528',
 '08717205546',
 '0871750',
 '08717507382',
 '08717509990',
 '08717890890',
 '08717895698',
 '08717898035',
 '08718711108',
 '08718720201',
 '08718723815',
 '08718725756',
 '08718726270',
 '087187262701',
 '08718726970',
 '08718726971',
 '08718726978',
 '087187272008',
 '08718727868',
 '08718727870',
 '08718727870150ppm',
 '08718730555',
 '08718730666',
 '08718738001',
 '08718738002',
 '08718738034',
 '08719180219',
 '08719180248',
 '08719181259',
 '08719181503',
 '08719181513',
 '08719839835',
 '08719899217',
 '08719899229',
 '08719899230',
 '09',
 '09041940223',
 '09050000301',
 '09050000332',
 '09050000460',
 '09050000555',
 '09050000878',
 '09050000928',
 '09050001295',
 '09050001808',
 '09050002311',
 '09050003091',
 '09050005321',
 '09050090044',
 '09050280520',
 '09053750005',
 '09056242159',
 '09057039994',
 '09058091854',
 '09058091870',
 '09058094454',
 '09058094455',
 '09058094507',
 '09058094565',
 '09058094583',
 '09058094594',
 '09058094597',
 '09058094599',
 '09058095107',
 '09058095201',
 '09058097189',
 '09058097218',
 '09058098002',
 '09058099801',
 '09061104276',
 '09061104283',
 '09061209465',
 '09061213237',
 '09061221061',
 '09061221066',
 '09061701444',
 '09061701461',
 '09061701851',
 '09061701939',
 '09061702893',
 '09061743386',
 '09061743806',
 '09061743810',
 '09061743811',
 '09061744553',
 '09061749602',
 '09061790121',
 '09061790125',
 '09061790126',
 '09063440451',
 '09063442151',
 '09063458130',
 '0906346330',
 '09064011000',
 '09064012103',
 '09064012160',
 '09064015307',
 '09064017295',
 '09064017305',
 '09064018838',
 '09064019014',
 '09064019788',
 '09065069120',
 '09065069154',
 '09065171142',
 '09065174042',
 '09065394514',
 '09065394973',
 '09065989180',
 '09065989182',
 '09066350750',
 '09066358152',
 '09066358361',
 '09066361921',
 '09066362206',
 '09066362220',
 '09066362231',
 '09066364311',
 '09066364349',
 '09066364589',
 '09066368327',
 '09066368470',
 '09066368753',
 '09066380611',
 '09066382422',
 '09066612661',
 '09066649731from',
 '09066660100',
 '09071512432',
 '09071512433',
 '09071517866',
 '09077818151',
 '09090204448',
 '09090900040',
 '09094100151',
 '09094646631',
 '09094646899',
 '09095350301',
 '09096102316',
 '09099725823',
 '09099726395',
 '09099726429',
 '09099726481',
 '09099726553',
 '09111030116',
 '09111032124',
 '09701213186',
 '0a',
 '0quit',
 '10',
 '100',
 '1000',
 '1000call',
 '1000s',
 '100p',
 '100percent',
 '100txt',
 '1013',
 '1030',
 '10am',
 '10k',
 '10p',
 '10ppm',
 '10th',
 '11',
 '1120',
 '113',
 '1131',
 '114',
 '1146',
 '116',
 '1172',
 '118p',
 '11mths',
 '11pm',
 '12',
 '1205',
 '120p',
 '121',
 '1225',
 '123',
 '125',
 '1250',
 '125gift',
 '128',
 '12hours',
 '12hrs',
 '12mths',
 '13',
 '130',
 '1327',
 '139',
 '14',
 '140',
 '1405',
 '140ppm',
 '145',
 '1450',
 '146tf150p',
 '14tcr',
 '14thmarch',
 '15',
 '150',
 '1500',
 '150p',
 '150p16',
 '150pm',
 '150ppermesssubscription',
 '150ppm',
 '150ppmpobox10183bhamb64xe',
 '150ppmsg',
 '150pw',
 '151',
 '153',
 '15541',
 '15pm',
 '16',
 '165',
 '1680',
 '169',
 '177',
 '18',
 '180',
 '1843',
 '18p',
 '18yrs',
 '195',
 '1956669',
 '1apple',
 '1b6a5ecef91ff9',
 '1cup',
 '1da',
 '1er',
 '1hr',
 '1im',
 '1lemon',
 '1mega',
 '1million',
 '1pm',
 '1st',
 '1st4terms',
 '1stchoice',
 '1stone',
 '1thing',
 '1tulsi',
 '1win150ppmx3',
 '1winaweek',
 '1winawk',
 '1x150p',
 '1yf',
 '20',
 '200',
 '2000',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '200p',
 '2025050',
 '20m12aq',
 '20p',
 '21',
 '21870000',
 '21st',
 '22',
 '220',
 '220cm2',
 '2309',
 '23f',
 '23g',
 '24',
 '24hrs',
 '24m',
 '24th',
 '25',
 '250',
 '250k',
 '255',
 '25p',
 '26',
 '2667',
 '26th',
 '27',
 '28',
 '2814032',
 '28days',
 '28th',
 '28thfeb',
 '29',
 '2b',
 '2bold',
 '2c',
 '2channel',
 '2day',
 '2docd',
 '2end',
 '2exit',
 '2ez',
 '2find',
 '2getha',
 '2geva',
 '2go',
 '2gthr',
 '2hook',
 '2hrs',
 '2i',
 '2kbsubject',
 '2lands',
 '2marrow',
 '2moro',
 '2morow',
 '2morro',
 '2morrow',
 '2morrowxxxx',
 '2mro',
 '2mrw',
 '2mwen',
 '2nd',
 '2nhite',
 '2nights',
 '2nite',
 '2optout',
 '2p',
 '2price',
 '2px',
 '2rcv',
 '2stop',
 '2stoptx',
 '2stoptxt',
 '2u',
 '2u2',
 '2watershd',
 '2waxsto',
 '2wks',
 '2wt',
 '2wu',
 '2years',
 '2yr',
 '2yrs',
 '30',
 '300',
 '3000',
 '300603',
 '300603t',
 '300p',
 '3030',
 '30apr',
 '30ish',
 '30pm',
 '30pp',
 '30s',
 '30th',
 '31',
 '3100',
 '310303',
 '31p',
 '32',
 '32000',
 '3230',
 '32323',
 '326',
 '33',
 '330',
 '350',
 '3510i',
 '35p',
 '3650',
 '36504',
 '3680',
 '373',
 '3750',
 '37819',
 '38',
 '382',
 '391784',
 '3aj',
 '3d',
 '3days',
 '3g',
 '3gbp',
 '3hrs',
 '3lions',
 '3lp',
 '3miles',
 '3mins',
 '3mobile',
 '3optical',
 '3pound',
 '3qxj9',
 '3rd',
 '3ss',
 '3uz',
 '3wks',
 '3x',
 '3xx',
 '40',
 '400',
 '400mins',
 '400thousad',
 '402',
 '4041',
 '40411',
 '40533',
 '40gb',
 '40mph',
 '41685',
 '41782',
 '420',
 '42049',
 '4217',
 '42478',
 '42810',
 '430',
 '434',
 '44',
 '440',
 '4403ldnw1a7rw18',
 '44345',
 '447797706009',
 '447801259231',
 '448712404000',
 '449050000301',
 '449071512431',
 '45',
 '450',
 '450p',
 '450ppw',
 '450pw',
 '45239',
 '45pm',
 '47',
 '4719',
 '4742',
 '47per',
 '48',
 '4882',
 '48922',
 '49',
 '49557',
 '4a',
 '4brekkie',
 '4d',
 '4eva',
 '4few',
 '4fil',
 '4get',
 '4give',
 '4got',
 '4goten',
 '4info',
 '4jx',
 '4msgs',
 '4mths',
 '4my',
 '4qf2',
 '4t',
 '4th',
 '4the',
 '4thnov',
 '4txt',
 '4u',
 '4utxt',
 '4w',
 '4ward',
 '4wrd',
 '4xx26',
 '4years',
 '50',
 '500',
 '5000',
 '505060',
 '50award',
 '50ea',
 '50gbp',
 '50p',
 '50perweeksub',
 '50perwksub',
 '50pm',
 '50pmmorefrommobile2bremoved',
 '50ppm',
 '50rcvd',
 '50s',
 '515',
 '5226',
 '523',
 '5249',
 '526',
 '528',
 '530',
 '54',
 '542',
 '545',
 '5digital',
 '5free',
 '5ish',
 '5k',
 '5min',
 '5mls',
 '5p',
 '5pm',
 '5th',
 '5wb',
 '5we',
 '5wkg',
 '5wq',
 '5years',
 '60',
 '600',
 '6031',
 '6089',
 '60p',
 '61',
 '61200',
 '61610',
 '62220cncl',
 '6230',
 '62468',
 '62735',
 '630',
 '63miles',
 '645',
 '65',
 '650',
 '66',
 '6669',
 '674',
 '67441233',
 '68866',
 '69101',
 '69200',
 '69669',
 '69696',
 '69698',
 '69855',
 '69866',
 '69876',
 '69888',
 '69888nyt',
 '69911',
 '69969',
 '69988',
 '6days',
 '6hl',
 '6hrs',
 '6ish',
 '6missed',
 '6months',
 '6ph',
 '6pm',
 '6th',
 '6times',
 '6wu',
 '6zf',
 '700',
 '71',
 '7250',
 '7250i',
 '730',
 '731',
 '74355',
 '75',
 '750',
 '7548',
 '75max',
 '762',
 '7634',
 '7684',
 '77',
 '7732584351',
 '78',
 '786',
 '7876150ppm',
 '79',
 '7am',
 '7cfca1a',
 '7ish',
 '7mp',
 '7oz',
 '7pm',
 '7th',
 '7ws',
 '7zs',
 '80',
 '800',
 '8000930705',
 '80062',
 '8007',
 '80082',
 '80086',
 '80122300p',
 '80155',
 '80160',
 '80182',
 '8027',
 '80488',
 '80608',
 '8077',
 '80878',
 '81010',
 '81151',
 '81303',
 '81618',
 '82050',
 '820554ad0a1705572711',
 '82242',
 '82277',
 '82324',
 '82468',
 '83021',
 '83039',
 '83049',
 '83110',
 '83118',
 '83222',
 '83332',
 '83338',
 '83355',
 '83370',
 '83383',
 '83435',
 '83600',
 '83738',
 '84',
 '84025',
 '84122',
 '84128',
 '84199',
 '84484',
 '85',
 '850',
 '85023',
 '85069',
 '85222',
 '85233',
 '8552',
 '85555',
 '86021',
 '861',
 '864233',
 '86688',
 '86888',
 '87021',
 '87066',
 '87070',
 '87077',
 '87121',
 '87131',
 '8714714',
 '872',
 '87239',
 '87575',
 '8800',
 '88039',
 '88066',
 '88088',
 '88222',
 '88600',
 '88800',
 '8883',
 '88877',
 '88888',
 '89034',
 '89070',
 '89080',
 '89105',
 '89123',
 '89545',
 '89555',
 '89693',
 '89938',
 '8am',
 '8ball',
 '8lb',
 '8p',
 '8pm',
 '8th',
 '8wp',
 '900',
 '9061100010',
 '910',
 '9153',
 '9280114',
 '92h',
 '930',
 '9307622',
 '945',
 '946',
 '95',
 '9755',
 '9758',
 '97n7qp',
 '98321561',
 '99',
 '9996',
 '9ae',
 '9am',
 '9ja',
 '9pm',
 '9t',
 '9th',
 '9yt',
 '____',
 'a21',
 'a30',
 'aa',
 'aah',
 'aaniye',
 'aaooooright',
 'aathi',
 'ab',
 'abbey',
 'abdomen',
 'abeg',
 'abel',
 'aberdeen',
 'abi',
 'ability',
 'abiola',
 'abj',
 'able',
 'abnormally',
 'about',
 'aboutas',
 'above',
 'abroad',
 'absence',
 'absolutely',
 'absolutly',
 'abstract',
 'abt',
 'abta',
 'aburo',
 'abuse',
 'abusers',
 'ac',
 'academic',
 'acc',
 'accent',
 'accenture',
 'accept',
 'access',
 'accessible',
 'accidant',
 'accident',
 'accidentally',
 'accommodation',
 'accommodationvouchers',
 'accomodate',
 'accomodations',
 'accordin',
 'accordingly',
 'account',
 'accounting',
 'accounts',
 'accumulation',
 'achan',
 'ache',
 'achieve',
 'acid',
 'acknowledgement',
 'acl03530150pm',
 'acnt',
 'aco',
 'across',
 'act',
 'acted',
 'actin',
 'acting',
 'action',
 'activ8',
 'activate',
 'active',
 'activities',
 'actor',
 'actual',
 'actually',
 'ad',
 'adam',
 'add',
 'addamsfa',
 'added',
 'addicted',
 'addie',
 'adding',
 'address',
 'adds',
 'adewale',
 'adi',
 'adjustable',
 'admin',
 'administrator',
 'admirer',
 'admission',
 'admit',
 'adore',
 'adoring',
 'adp',
 'adress',
 'adrian',
 'adrink',
 'ads',
 'adsense',
 'adult',
 'adults',
 'advance',
 'adventure',
 'adventuring',
 'advice',
 'advise',
 'advising',
 'advisors',
 'aeronautics',
 'aeroplane',
 'afew',
 'affair',
 'affairs',
 'affection',
 'affectionate',
 'affections',
 'affidavit',
 'afford',
 'afghanistan',
 'afraid',
 'africa',
 'african',
 'aft',
 'after',
 'afternon',
 'afternoon',
 'afternoons',
 'afterwards',
 'aftr',
 'ag',
 'again',
 'against',
 'agalla',
 'age',
 'age16',
 'age23',
 'agency',
 'agent',
 'agents',
 'ages',
 'agidhane',
 'aging',
 'ago',
 'agree',
 'ah',
 'aha',
 'ahead',
 'ahhh',
 ...]

In [11]:
#tranformm training data into a "document term matrix"
sms_dtm=vect.transform(df.SMS)
sms_dtm

<5572x8713 sparse matrix of type '<class 'numpy.int64'>'
	with 74169 stored elements in Compressed Sparse Row format>

In [12]:
print(sms_dtm)

  (0, 1082)	1
  (0, 1316)	1
  (0, 1765)	1
  (0, 1767)	1
  (0, 2061)	1
  (0, 2338)	1
  (0, 3571)	1
  (0, 3615)	1
  (0, 3655)	1
  (0, 4114)	1
  (0, 4374)	1
  (0, 4501)	1
  (0, 5571)	1
  (0, 5958)	1
  (0, 7694)	1
  (0, 8084)	1
  (0, 8324)	1
  (0, 8548)	1
  (1, 4342)	1
  (1, 4537)	1
  (1, 5538)	1
  (1, 5567)	1
  (1, 8450)	1
  (2, 77)	1
  (2, 403)	1
  :	:
  (5570, 1794)	1
  (5570, 1802)	1
  (5570, 2606)	1
  (5570, 2905)	1
  (5570, 3323)	1
  (5570, 3373)	1
  (5570, 3489)	1
  (5570, 3709)	1
  (5570, 3805)	1
  (5570, 4114)	1
  (5570, 4188)	1
  (5570, 4245)	1
  (5570, 4642)	1
  (5570, 5367)	1
  (5570, 7089)	1
  (5570, 7099)	1
  (5570, 7674)	1
  (5570, 7806)	1
  (5570, 8120)	1
  (5570, 8371)	1
  (5571, 4253)	2
  (5571, 5276)	1
  (5571, 6548)	1
  (5571, 7806)	1
  (5571, 7938)	1

In [13]:
#convert sparse matrix to a dense matrix
sms_dtm.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [14]:
#examine the vocabulary and document term matrix together
df1=pd.DataFrame(sms_dtm.toarray(),columns=vect.get_feature_names())
df1.head()

,00,000,000pes,008704050406,0089,0121,01223585236,01223585334,0125698789,02,...,zhong,zindgi,zoe,zogtorius,zoom,zouk,zyada,èn,ú1,〨ud
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
df1.shape

(5572, 8713)

In [16]:
x=df.SMS
x.head()

0    Go until jurong point, crazy.. Available only ...
1                        Ok lar... Joking wif u oni...
2    Free entry in 2 a wkly comp to win FA Cup fina...
3    U dun say so early hor... U c already then say...
4    Nah I don't think he goes to usf, he lives aro...
Name: SMS, dtype: object

In [17]:
y=df.label
y.head()

0    0
1    0
2    1
3    0
4    0
Name: label, dtype: int64

# training the model

In [18]:
#split x and y into training and testing sets
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=10)

In [19]:
print(x_train.shape,x_test.shape)

(4179,) (1393,)

In [20]:
print(y_train.shape,y_test.shape)

(4179,) (1393,)

In [21]:
from sklearn.feature_extraction.text import CountVectorizer
vect=CountVectorizer()

In [22]:
vect.fit(x_train)
x_train_dtm=vect.transform(x_train)

#x_train_dtm=vect.fit_tranform(x_train)

In [23]:
x_train_dtm

<4179x7445 sparse matrix of type '<class 'numpy.int64'>'
	with 55620 stored elements in Compressed Sparse Row format>

In [24]:
print(x_train_dtm)

  (0, 2291)	1
  (0, 2969)	1
  (0, 3484)	1
  (0, 3604)	1
  (0, 4775)	1
  (0, 6052)	1
  (0, 7414)	1
  (1, 947)	1
  (1, 4031)	1
  (2, 2914)	1
  (2, 3208)	1
  (2, 3478)	1
  (2, 5859)	1
  (2, 7319)	1
  (3, 388)	1
  (3, 1094)	1
  (3, 1497)	1
  (3, 1819)	1
  (3, 2545)	1
  (3, 2552)	1
  (3, 2597)	1
  (3, 3053)	1
  (3, 3276)	1
  (3, 3339)	1
  (3, 3395)	1
  :	:
  (4176, 3981)	1
  (4176, 4023)	1
  (4176, 4180)	1
  (4176, 4213)	1
  (4176, 4221)	1
  (4176, 4401)	1
  (4176, 4474)	1
  (4176, 4634)	1
  (4176, 5216)	1
  (4176, 5682)	1
  (4176, 6042)	1
  (4176, 6571)	1
  (4176, 6576)	1
  (4177, 1543)	1
  (4177, 1616)	1
  (4177, 2725)	1
  (4177, 2750)	1
  (4177, 6539)	1
  (4177, 6562)	1
  (4177, 6657)	1
  (4178, 3188)	1
  (4178, 4565)	1
  (4178, 6657)	1
  (4178, 6697)	1
  (4178, 7381)	1

In [25]:
x_test_dtm=vect.transform(x_test)
x_test_dtm

<1393x7445 sparse matrix of type '<class 'numpy.int64'>'
	with 17122 stored elements in Compressed Sparse Row format>

In [26]:
print(x_test_dtm)

  (0, 2253)	1
  (0, 3208)	1
  (0, 4398)	1
  (0, 4412)	1
  (0, 4735)	1
  (0, 6557)	1
  (0, 6657)	2
  (0, 7281)	1
  (1, 574)	1
  (1, 679)	1
  (1, 1135)	1
  (1, 3301)	1
  (1, 3893)	1
  (1, 4570)	1
  (1, 4746)	1
  (1, 4884)	1
  (1, 5043)	1
  (1, 6425)	1
  (2, 907)	1
  (2, 1740)	1
  (2, 2143)	1
  (2, 2290)	1
  (2, 7191)	1
  (2, 7254)	1
  (2, 7408)	1
  :	:
  (1391, 4825)	1
  (1391, 5052)	1
  (1391, 5484)	1
  (1391, 5912)	1
  (1391, 5918)	1
  (1391, 6134)	1
  (1391, 6286)	1
  (1391, 7414)	1
  (1392, 289)	1
  (1392, 648)	1
  (1392, 1511)	1
  (1392, 2422)	1
  (1392, 2535)	1
  (1392, 3234)	1
  (1392, 3673)	1
  (1392, 4003)	1
  (1392, 4051)	2
  (1392, 4056)	1
  (1392, 4599)	1
  (1392, 5067)	1
  (1392, 5765)	1
  (1392, 6657)	1
  (1392, 6818)	1
  (1392, 6919)	1
  (1392, 7372)	1

# building the model

In [27]:
#import and instantiate  a multinomial naive bayes model
from sklearn.naive_bayes import MultinomialNB
nb=MultinomialNB()

In [28]:
#train the model using x_train_dtm
%time
nb.fit(x_train_dtm,y_train)

Wall time: 0 ns

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [29]:
#make class predictions for x_test_dtm
y_pred_class=nb.predict(x_test_dtm)

In [36]:
#calculate accuracy of class predictions
from sklearn.metrics import accuracy_score,confusion_matrix,roc_auc_score
accuracy=accuracy_score(y_test,y_pred_class)
accuracy

0.9820531227566404

In [31]:
cm=confusion_matrix(y_test,y_pred_class)
cm

array([[1209,    6],
       [  19,  159]], dtype=int64)

In [32]:
#print message text for the false positives(ham incorrectly as spam)
x_test[y_test<y_pred_class]

1506    Total video converter free download type this ...
5475    Dhoni have luck to win some big title.so we wi...
4702                               I liked the new mobile
4703                                           Anytime...
2173     Yavnt tried yet and never played original either
4557                              Gettin rdy to ship comp
Name: SMS, dtype: object

In [33]:
#print message text for the false negatives(spam incorrectly as ham)
x_test[y_test>y_pred_class]

955             Filthy stories and GIRLS waiting for your
1875    Would you like to see my XXX pics they are so ...
1638    0A$NETWORKS allow companies to bill for SMS, s...
2663    Hello darling how are you today? I would love ...
1269    Can U get 2 phone NOW? I wanna chat 2 set up m...
2558    This message is brought to you by GMW Ltd. and...
1940    More people are dogging in your area now. Call...
68      Did you hear about the new "Divorce Barbie"? I...
869     Hello. We need some posh birds and chaps to us...
1469    Hi its LUCY Hubby at meetins all day Fri & I w...
4676    Hi babe its Chloe, how r u? I was smashed on s...
1663    Hi if ur lookin 4 saucy daytime fun wiv busty ...
4949    Hi this is Amy, we will be sending you a free ...
856     Talk sexy!! Make new friends or fall in love i...
3530    Xmas & New Years Eve tickets are now on sale f...
3742                                        2/2 146tf150p
3460    Not heard from U4 a while. Call me now am here...
2823    ROMCAPspam Everyone around should be respondin...
2352    Download as many ringtones as u like no restri...
Name: SMS, dtype: object

In [34]:
#calculate predicted probabilities for x_test_dtm
y_pred_prob=nb.predict_proba(x_test_dtm)[:,1]
print(y_pred_prob)

[1.53717337e-01 9.13374965e-02 1.34387638e-04 ... 8.08903211e-05
 3.70279416e-07 9.99032891e-01]

In [37]:
#calculate auc
roc_auc_score(y_test,y_pred_prob)

0.9649211633606141

In [39]:
#store the vocabulary of x_train
x_train_tokens=vect.get_feature_names()
len(x_train_tokens)

7445

In [43]:
# examine the first 50 tokens
print(x_train_tokens[0:50])

['00', '000', '008704050406', '0089', '0121', '01223585334', '02', '0207', '02085076972', '021', '03', '04', '0430', '05', '050703', '0578', '06', '07', '07008009200', '07046744435', '07090201529', '07090298926', '07099833605', '0721072', '07734396839', '07742676969', '07753741225', '0776xxxxxxx', '07781482378', '07786200117', '077xxx', '078', '07801543489', '07808', '07808726822', '07815296484', '07821230901', '078498', '0789xxxxxxx', '0796xxxxxx', '07973788240', '07xxxxxxxxx', '08', '0800', '08000407165', '08000776320', '08000839402', '08000930705', '08000938767', '08001950382']

In [44]:
# examine the last 50 tokens
print(x_train_tokens[-50:])

['yet', 'yetty', 'yetunde', 'yhl', 'yifeng', 'yijue', 'ym', 'ymca', 'yo', 'yoga', 'yogasana', 'yor', 'yorge', 'you', 'youdoing', 'youi', 'young', 'younger', 'youphone', 'your', 'youre', 'yourinclusive', 'yourjob', 'yours', 'yourself', 'youuuuu', 'youwanna', 'yoville', 'yowifes', 'yr', 'yrs', 'ystrday', 'ything', 'yummmm', 'yummy', 'yun', 'yunny', 'yup', 'yupz', 'zac', 'zaher', 'zealand', 'zebra', 'zed', 'zeros', 'zhong', 'zoe', 'zogtorius', 'ú1', '〨ud']

In [40]:
#no. of times each token appears accross all ham msgs
ham_token_count=nb.feature_count_[0,:]
ham_token_count

array([0., 0., 0., ..., 1., 0., 1.])

In [41]:
#no. of times each token appears accross all spam msgs
spam_token_count=nb.feature_count_[1,:]
spam_token_count

array([ 6., 24.,  2., ...,  0.,  1.,  0.])

In [45]:
#create dataframe of tokens with their separate ham and spam counts
tokens=pd.DataFrame({"token":x_train_tokens,"ham":ham_token_count,"spam":spam_token_count}).set_index('token')
tokens.head(100)

                 ham  spam
token
00               0.0   6.0
000              0.0  24.0
008704050406     0.0   2.0
0089             0.0   1.0
0121             0.0   1.0
01223585334      0.0   1.0
02               0.0   5.0
0207             0.0   3.0
02085076972      0.0   1.0
021              0.0   2.0
03               0.0   8.0
04               0.0  10.0
0430             0.0   1.0
05               0.0   5.0
050703           0.0   2.0
0578             0.0   1.0
06               0.0   4.0
07               0.0   2.0
07008009200      0.0   1.0
07046744435      0.0   1.0
07090201529      0.0   1.0
07090298926      0.0   1.0
07099833605      0.0   1.0
0721072          0.0   1.0
07734396839      0.0   2.0
07742676969      0.0   1.0
07753741225      0.0   1.0
0776xxxxxxx      0.0   1.0
07781482378      0.0   2.0
07786200117      0.0   1.0
...              ...   ...
08701237397      0.0   1.0
08701417012      0.0   1.0
08701417012150p  0.0   2.0
0870141701216    0.0   1.0
087016248        0.0   1.0
087018728737     0.0   1.0
0870241182716    0.0   1.0
08702840625      0.0   3.0
08704050406      0.0   1.0
08704439680      0.0   1.0
08706091795      0.0   2.0
08707509020      0.0   5.0
0870753331018    0.0   1.0
08707808226      0.0   1.0
08708034412      0.0   2.0
08709222922      0.0   1.0
0871             0.0   3.0
087104711148     0.0   1.0
08712101358      0.0   2.0
0871212025016    0.0   1.0
08712300220      0.0   4.0
087123002209am   0.0   1.0
08712317606      0.0   2.0
08712400602450p  0.0   2.0
08712400603      0.0   1.0
08712402050      0.0   2.0
08712402578      0.0   1.0
08712402779      0.0   1.0
08712402902      0.0   1.0
08712402972      0.0   1.0

[100 rows x 2 columns]

In [113]:
#naive bayes counts the no. of observation in each class
nb.class_count_

array([3610.,  569.])

In [48]:
# examine 5 random DataFrame rows
tokens.sample(10, )

                ham  spam
token
effect          1.0   0.0
fyi             4.0   0.0
canal           2.0   0.0
outsomewhere    1.0   0.0
fireplace       1.0   0.0
of            382.0  72.0
aretaking       1.0   0.0
rite           14.0   0.0
gods            2.0   0.0
mindset         1.0   0.0

Before we can calculate the "spamminess" of each token, we need to avoid **dividing by zero** and account for the **class imbalance**.

In [49]:
# add 1 to ham and spam counts to avoid dividing by 0
tokens['ham'] = tokens.ham + 1
tokens['spam'] = tokens.spam + 1
tokens.sample(5, random_state=6)

          ham  spam
token
lac       2.0   1.0
clearing  2.0   1.0
hitter    2.0   1.0
ideas     3.0   1.0
ls15hb    1.0   2.0

In [50]:
# convert the ham and spam counts into frequencies
tokens['ham'] = tokens.ham / nb.class_count_[0]
tokens['spam'] = tokens.spam / nb.class_count_[1]
tokens.sample(5, random_state=6)

               ham      spam
token
lac       0.000554  0.001757
clearing  0.000554  0.001757
hitter    0.000554  0.001757
ideas     0.000831  0.001757
ls15hb    0.000277  0.003515

In [51]:
# calculate the ratio of spam-to-ham for each token
tokens['spam_ratio'] = tokens.spam / tokens.ham
tokens.sample(5, random_state=6)

               ham      spam  spam_ratio
token
lac       0.000554  0.001757    3.172232
clearing  0.000554  0.001757    3.172232
hitter    0.000554  0.001757    3.172232
ideas     0.000831  0.001757    2.114821
ls15hb    0.000277  0.003515   12.688928

In [53]:
# examine the DataFrame sorted by spam_ratio
tokens.sort_values('spam_ratio', ascending=False)

                 ham      spam  spam_ratio
token
claim       0.000277  0.144112  520.246046
prize       0.000277  0.124780  450.456942
150p        0.000277  0.100176  361.634446
tone        0.000277  0.089631  323.567663
18          0.000277  0.079086  285.500879
www         0.000554  0.151142  272.811951
500         0.000277  0.073814  266.467487
guaranteed  0.000277  0.072056  260.123023
cs          0.000277  0.063269  228.400703
uk          0.000554  0.115993  209.367311
1000        0.000277  0.056239  203.022847
awarded     0.000277  0.056239  203.022847
award       0.000277  0.045694  164.956063
entry       0.000277  0.045694  164.956063
000         0.000277  0.043937  158.611599
ringtone    0.000277  0.043937  158.611599
150ppm      0.000277  0.043937  158.611599
tones       0.000277  0.042179  152.267135
code        0.000277  0.040422  145.922671
collection  0.000277  0.040422  145.922671
weekly      0.000277  0.038664  139.578207
10p         0.000277  0.036907  133.233743
16          0.000554  0.073814  133.233743
mob         0.000277  0.036907  133.233743
sae         0.000277  0.035149  126.889279
800         0.000277  0.033392  120.544815
5000        0.000277  0.033392  120.544815
vouchers    0.000277  0.033392  120.544815
http        0.000277  0.033392  120.544815
national    0.000277  0.033392  120.544815
...              ...       ...         ...
ll          0.052632  0.007030    0.133568
much        0.026316  0.003515    0.133568
gonna       0.013296  0.001757    0.132176
where       0.026870  0.003515    0.130814
gud         0.013573  0.001757    0.129479
sleep       0.014127  0.001757    0.124401
feel        0.014127  0.001757    0.124401
something   0.014404  0.001757    0.122009
my          0.159003  0.017575    0.110531
anything    0.016066  0.001757    0.109387
lol         0.016066  0.001757    0.109387
sure        0.016343  0.001757    0.107533
come        0.049861  0.005272    0.105741
cos         0.017729  0.001757    0.099132
morning     0.017729  0.001757    0.099132
amp         0.018283  0.001757    0.096128
ask         0.018560  0.001757    0.094693
doing       0.018560  0.001757    0.094693
home        0.037673  0.003515    0.093301
said        0.020222  0.001757    0.086910
ok          0.062050  0.005272    0.084970
way         0.021330  0.001757    0.082396
later       0.026870  0.001757    0.065407
did         0.028255  0.001757    0.062201
da          0.033241  0.001757    0.052871
she         0.033241  0.001757    0.052871
lor         0.034903  0.001757    0.050353
he          0.049584  0.001757    0.035444
lt          0.068144  0.001757    0.025791
gt          0.068975  0.001757    0.025480

[7445 rows x 3 columns]

In [59]:
# look up the spam_ratio for a given token
tokens.loc['dating', 'spam_ratio']

95.16695957820738

# using logistic regression

In [97]:
from sklearn.linear_model import LogisticRegression
logreg=LogisticRegression()

In [98]:
%time
logreg.fit(x_train_dtm,y_train)

Wall time: 0 ns

C:\Users\Jayashree\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [99]:
y_pred=logreg.predict(x_test_dtm)

In [100]:
accuracy_score(y_test,y_pred)

0.9741564967695621

# random forest

In [101]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()

In [102]:
rfc.fit(x_train_dtm,y_train)

C:\Users\Jayashree\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [104]:
rfc_pred=rfc.predict(x_test_dtm)

In [105]:
accuracy_score(y_test,rfc_pred)

0.9597989949748744